routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::group(['middleware' => 'guest'], function() {
    Route::get('/', function(){
        return redirect('https://ae.laligacademy.com/online/');
    });

//});


//Auth::routes(['verify' => true]);
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('login', function(){
    return redirect('https://ae.laligacademy.com/online/login/');
});

//Route::get('/live-stream', function(){
//    return view('players.live_stream');
//});
Route::get('/redirectToUserHome', 'Auth\LoginController@redirectToUserHome');


Route::get('payments/redirectTo/{action}', 'PaymentsController@redirectRoutes');
Route::post('payments/redirectTo/{action}', 'PaymentsController@redirectRoutes')->name('players.payments.redirect_routes');

Route::name('coach.')->prefix('coach/')->group(function() {
    Route::group(['middleware' => 'guest'], function() {
//        Route::get('/', function () {
//            return redirect()->route('coach.login');
//        });
//        Route::get('/login', function () {
//            return view('auth.login');
//        })->name('login');
    });
    Route::group(['middleware' => 'coach'], function() {
        Route::get( '/dashboard', 'CoachesController@dashboard')
            ->name('dashboard');
        Route::get('/profile', 'CoachesController@profile')->name('profile');
        Route::post('/profile', 'CoachesController@profileUpdate')
            ->name('profile_update');

        Route::get('courses', 'CoursesController@index')->name('courses.index');

        Route::get('players', 'PlayersController@index')->name('players.index');

        Route::name('courses.')->group(function() {
            Route::resource('courses/{course}/videos', 'VideosController');
            Route::resource('courses/{course}/questionnaires', 'QuestionnairesController');
            Route::name('questionnaires.')->group(function() {
                Route::resource('courses/{course}/questionnaires/{questionnaire}/quizzes',
                    'QuizzesController');

                Route::get('courses/{course}/questionnaires/{questionnaire}/submissions/',
                    'QuestionnairesController@submissionsIndex')->name('submissions.index');

                Route::get('courses/{course}/questionnaires/{questionnaire}/submissions/{submission}',
                    'QuestionnairesController@submissionsShow')->name('submissions.show');
            });
            Route::post('courses/{course}/update_settings', 'CoursesController@updateSettings')->name('update_settings');

            Route::get('courses/{course}/videos/{video}/uploads', 'UploadsController@index')->name('videos.uploads.index');

        });
    });
});
Route::get('/gtK5fZS15jkj5QT8jV5l7jY3uJk0UFba4qnYtzy0', 'AdminsController@login');
Route::get('7jY3uJk0UFba4qnY', function(){
    http_response_code(404);
    die();
})->name('login');
Route::post('7jY3uJk0UFba4qnY', 'Auth\LoginController@login');
Route::name('admin.')->prefix('admin/')->group(function() {
    Route::group(['middleware' => 'guest'], function() {
//        Route::get('/', function () {
//            return redirect()->route('admin.login');
//        });
//        Route::get('/login', function () {
//            return view('auth.login');
//        })->name('login');

    });
    Route::group(['middleware' => 'admin'], function() {
        Route::get( '/dashboard', 'AdminsController@dashboard')
            ->name('dashboard');
        Route::get('/profile', 'AdminsController@profile')
            ->name('profile');
        Route::post('/profile', 'AdminsController@profileUpdate')
            ->name('profile_update');

        Route::get('coaches', 'CoachesController@index')->name('coaches.index');
        Route::get('coaches/create', 'CoachesController@create')->name('coaches.create');
        Route::post('coaches', 'CoachesController@store')->name('coaches.store');
        Route::get('coaches/{coach}/edit', 'CoachesController@edit')->name('coaches.edit');
        Route::match(['put', 'patch'],'coaches/{coach}', 'CoachesController@update')->name('coaches.update');

        Route::resource('courses', 'CoursesController');
        Route::get('courses/{course}/assign_coaches', 'CoursesController@assignCoaches')->name('courses.assign_coaches');
        Route::post('courses/{course}/assign_coaches', 'CoursesController@assignCoachesUpdate')->name('courses.assign_coaches_update');

        Route::get('players', 'PlayersController@index')->name('players.index');
        Route::get('players/export', 'PlayersController@exportAll')->name('players.export_all');
        Route::post('players/{player}/updatePaymentStatus', 'PlayersController@updatePaymentStatus')->name('players.update_payment_status');
    });
});

Route::post('/auth/verifyLogin', 'Auth\LoginController@verifyLogin');
Route::get('/auth/doLogin/{id}', 'Auth\LoginController@doLogin');

Route::group(['middleware' => 'player'], function(){

    Route::get('/{session_id}/schedule', 'PlayersController@schedule')->name('schedule');
    Route::get('/{session_id}/terms-conditions', 'PlayersController@termsConditions')->name('terms_conditions');

    Route::get( '/{session_id}/dashboard', 'PlayersController@dashboard')
        ->name('dashboard');

    Route::name('players.')->group(function() {
        Route::get('/{session_id}/profile', 'PlayersController@profile')
            ->name('profile');
        Route::post('/{session_id}/profile', 'PlayersController@profileUpdate')
            ->name('profile_update');
        Route::get('/{session_id}/courses/{course}', 'CoursesController@show')->name('courses.show');
        Route::get('/{session_id}/courses/{course}/videos/{video}', 'VideosController@show')->name('courses.videos.show');
        Route::post('/{session_id}/courses/{course}/videos/{video}/like', 'VideosController@like')->name('courses.videos.like');
        Route::post('/{session_id}/courses/{course}/videos/{video}/uploads', 'UploadsController@store')->name('courses.videos.upload');

        Route::get('/{session_id}/courses/{course}/questionnaires', 'QuestionnairesController@playersIndex')->name('courses.questionnaires.index');
        Route::get('/{session_id}/courses/{course}/questionnaires/{questionnaire}', 'QuestionnairesController@playersShow')->name('courses.questionnaires.show');
        Route::post('/{session_id}/courses/{course}/questionnaires/{questionnaire}', 'QuestionnairesController@playersStore')->name('courses.questionnaires.store');

        Route::get('/payments/success', 'PaymentsController@success')->name('payments.success');
        Route::get('/payments/failure', 'PaymentsController@failure')->name('payments.failure');

        Route::get('/{session_id}/payments/{course}', 'PaymentsController@create')->name('payments.create');
        Route::post('/{session_id}/payments/{course}/checkout/{package}', 'PaymentsController@checkout')->name('payments.checkout');


    });

});

Route::get('/lout', function(){
    Auth::logout();
});

Route::get('/clear-cache', function() {
    Artisan::call('view:clear');
    return "Cache is cleared";
});

app/Payment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    public function course(){
        return $this->belongsTo(Course::class);
    }
}

app/Http/Controllers/PaymentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use App\Course;
use App\Payment;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Utilities\Payfort;

class PaymentsController extends Controller
{

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($session_id, Course $course)
    {
        if($course->isPurchased()){
            // Redirect to Course Page
            return redirect()->route('players.courses.show', [session('session_id'), $course]);
        }

        $dates = [
            'today' => Carbon::now(),
            'coming_sunday' => Carbon::parse('next sunday'),
            'day_after_1_week' => Carbon::parse('next sunday')->addWeeks(1)->subDay(1),
            'day_after_4_weeks' => Carbon::parse('next sunday')->addWeeks(4)->subDay(1),
            'day_after_8_weeks' => Carbon::parse('next sunday')->addWeeks(8)->subDay(1),
        ];
        return view('payments.create', compact('course', 'dates'));
    }

    public function checkout(Request $request, $session_id, Course $course, $package)
    {
        $dates = [
            'coming_sunday' => Carbon::parse('next sunday'),
            'day_after_1_week' => Carbon::parse('next sunday')->addWeeks(1)->subDay(1),
            'day_after_4_weeks' => Carbon::parse('next sunday')->addWeeks(4)->subDay(1),
            'day_after_8_weeks' => Carbon::parse('next sunday')->addWeeks(8)->subDay(1),
        ];

        if($package == 1) { // 4 Weeks
            $total_amount = 830;
            $item_name = $course->title . ' - ' . '4 Weeks Payment';
            $end_date = $dates['day_after_4_weeks'];
        } else if($package == 2) { // 8 Weeks
            $total_amount = 1425;
            $item_name = $course->title . ' - ' . '8 Weeks Payment';
            $end_date = $dates['day_after_8_weeks'];
        } else if($package == 3) { // 1 Week
            $total_amount = 210;
            $item_name = $course->title . ' - ' . '1 Week Payment';
            $end_date = $dates['day_after_1_week'];
        } else {
            // Redirect to payment page
            return redirect('players.payments.create', [session('session_id'), $course]);
        }

        // Save Payment Details in DB
        $payment = new Payment;
        $payment->order_details = $item_name;
        $payment->amount = $total_amount;
        $payment->start_date = $dates['coming_sunday'];
        $payment->end_date = $end_date;
        $payment->user_id = Auth::user()->id;
        $payment->course_id = $course->id;
        $payment->save();


        // Setting variables
//        session([
//            'payment_id' => $payment->id,
//            'user_email' => Auth::user()->email,
//            'user_name' => Auth::user()->name,
//            'total_amount' => $total_amount,
//            'item_name' => $item_name
//        ]);

        $payment_id = $payment->id;

        return view('payments.checkout', compact('course', 'payment_id', 'total_amount', 'item_name'));
    }

    public function redirectRoutes($action){
        if(!isset($action)) {
            echo 'Page Not Found!';
            exit;
        }
        $objFort = new Payfort();
        if($action == 'getPaymentPage') {
            $objFort->processRequest(htmlspecialchars($_REQUEST['paymentMethod'], ENT_QUOTES, 'UTF-8'));
        }
        elseif($action == 'merchantPageReturn') {
            $objFort->processMerchantPageResponse();
        }
        elseif($action == 'processResponse') {
            $objFort->processResponse();
        }
        else{
            echo 'Page Not Found!';
            exit;
        }
    }

    public function success(Request $request)
    {
//        dd($request->all());
        $payment = Payment::find($this->getPaymentIdFromMerchant($request['merchant_extra']));
        $course = null;
        if($payment) {
            $course = $payment->course;
            if(empty($payment->transaction_reference)){
                $payment->transaction_details = json_encode(request()->all());
                $payment->status = 1;
                $payment->transaction_reference = json_encode($request['fort_id']);
                $payment->save();
            }
        }
        $session_id = session('session_id');
        return view('payments.success', ['response' => $request->all(), 'course' => $course, 'session_id' => $session_id]);
    }

    public function failure(Request $request)
    {
//        dd($request->all());
        $payment = Payment::find($this->getPaymentIdFromMerchant($request['merchant_extra']));
        $course = null;
        if($payment) {
            $course = $payment->course;
            if(empty($payment->transaction_reference)){
                $payment->transaction_details = json_encode(request()->all());
                $payment->save();
            }
        }
        $session_id = session('session_id');
        return view('payments.failure', ['response' => $request->all(), 'course' => $course, 'session_id' => $session_id]);
    }

    protected function getPaymentIdFromMerchant($merchant_extra)
    {
        return (int)substr($merchant_extra, 4);
    }
}

resources/views/payments/checkout.blade.php
@extends('layouts.app')

@section('content')
    @include('partials._header')
    <section class="dashboard-layout bg-grey">

        <section class="dashboard-body">
            <div class="container">
                <h2 class="form-title text-center">{{ $course->title }} - Payment Processing</h2>
                <form action="https://ae.laligacademy.com/payment/laligacademyOnlineCheckout" method="POST" id="paymentForm">
                    <input type="hidden" name="payment_id" value="{{ $payment_id }}" />
                    <input type="hidden" name="user_email" value="{{ Auth::user()->email }}" />
                    <input type="hidden" name="user_name" value="{{ Auth::user()->name }}" />
                    <input type="hidden" name="total_amount" value="{{ $total_amount }}" />
                    <input type="hidden" name="item_name" value="{{ $item_name }}" />
                </form>
            </div>
        </section>

        @include('partials._socialfooter')

    </section>
@endsection

@section('footer-scripts')
    {{--<script type="text/javascript" src="{{ asset('assets-web/js/checkout.js') }}"></script>
    <script>
        $(document).ready(function(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-Token': '{{ csrf_token() }}'
                }
            });
            getPaymentPage('creditcard');
        });
    </script>--}}
    <script>
        $(window).load(function(){
            $('#paymentForm').submit();
        });
    </script>
@endsection

resources/views/payments/create.blade.php
@extends('layouts.app')

@section('content')
    @include('partials._header')

    <section class="dashboard-layout bg-grey">

        <section class="dashboard-body">
            <div class="container">
                <h2 class="form-title text-center">{{ $course->title }} - Payment</h2>
                <div class="row">

                    <div class="col-md-4 offset-md-4">
                        <div class="box --payment-box">
                            <h4 class="title">1 Week Payment</h4>
                            <p class="price">
                                <strong>210.00 AED</strong>
                            </p>
                            <p class="date">
                                <strong>{{ $dates['coming_sunday']->format('d/m/Y') }}</strong>
                                to
                                <strong>{{ $dates['day_after_1_week']->format('d/m/Y') }}</strong>
                            </p>

                            <form action="{{ route('players.payments.checkout', [session('session_id'), $course, 3]) }}" method="post">
                                @csrf
                                <button type="submit" class="btn --btn-primary">Pay Now</button>
                            </form>
                        </div>
                    </div>

                    {{--<div class="col-md-4">
                        <div class="box --payment-box">
                            <h4 class="title">4 Weeks Payment</h4>
                            <p class="price">
                                <strong>830.00 AED</strong>
                                <strong>320.00 CAD</strong>
                            </p>
                            <p class="date">
                                <strong>{{ $dates['coming_sunday']->format('d/m/Y') }}</strong>
                                to
                                <strong>{{ $dates['day_after_4_weeks']->format('d/m/Y') }}</strong>
                            </p>

                            <form action="{{ route('players.payments.checkout', [$course, 1]) }}" method="post">
                                @csrf
                                <button type="submit" class="btn --btn-primary">Pay Now</button>
                            </form>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="box --payment-box">
                            <h4 class="title">8 Weeks Payment</h4>
                            <p class="price">
                                <strong>1425.00 AED</strong>
                                <strong>550.00 CAD</strong>
                            </p>
                            <p class="date">
                                <strong>{{ $dates['coming_sunday']->format('d/m/Y') }}</strong>
                                to
                                <strong>{{ $dates['day_after_8_weeks']->format('d/m/Y') }}</strong>
                            </p>

                            <form action="{{ route('players.payments.checkout', [$course, 2]) }}" method="post">
                                @csrf
                                <button type="submit" class="btn --btn-primary">Pay Now</button>
                            </form></button>
                        </div>
                    </div>--}}

                </div>
            </div>
        </section>

        @include('partials._socialfooter')

    </section>
@endsection

@section('footer-scripts')
    <script>
        $(document).ready(function(){
        });
    </script>
@endsection

resources/views/payments/failure.blade.php
@extends('layouts.app')

@section('content')
    @include('partials._header')
    <section class="dashboard-layout bg-grey">

        <section class="dashboard-body">
            <div class="container">
                <h2 class="form-title text-center">
                    @if(isset($course->title)) {{ $course->title.' - ' }} @endif
                        Payment Failed</h2>
                <p>
                    @if($course)
                    <a href="{{ route('players.courses.show', [$session_id, $course]) }}">Click here to go back to Payment Page</a>
                        @else
                        <a href="{{ route('dashboard', [$session_id]) }}">Click here to go back to Courses Page.</a>
                    @endif
                </p>
            </div>
        </section>

        @include('partials._socialfooter')

    </section>
@endsection

@section('footer-scripts')
    <script>
        $(document).ready(function(){
        });
    </script>
@endsection

resources/views/payments/success.blade.php
@extends('layouts.app')

@section('content')
    @include('partials._header')
    <section class="dashboard-layout bg-grey">

        <section class="dashboard-body">
            <div class="container">
                <h2 class="form-title text-center">{{ $course->title }} - Payment Successful</h2>
                <p>
                    <a href="{{ route('players.courses.show', [$session_id, $course]) }}">Click here to go back to Course Page</a>
                </p>
            </div>
        </section>

        @include('partials._socialfooter')

    </section>
@endsection

@section('footer-scripts')
    <script>
        $(document).ready(function(){
        });
    </script>
@endsection