routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::group(['middleware' => 'guest'], function() {
    Route::get('/', function(){
        return redirect('https://ae.laligacademy.com/online/');
    });

//});


//Auth::routes(['verify' => true]);
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('login', function(){
    return redirect('https://ae.laligacademy.com/online/login/');
});

//Route::get('/live-stream', function(){
//    return view('players.live_stream');
//});
Route::get('/redirectToUserHome', 'Auth\LoginController@redirectToUserHome');


Route::get('payments/redirectTo/{action}', 'PaymentsController@redirectRoutes');
Route::post('payments/redirectTo/{action}', 'PaymentsController@redirectRoutes')->name('players.payments.redirect_routes');

Route::name('coach.')->prefix('coach/')->group(function() {
    Route::group(['middleware' => 'guest'], function() {
//        Route::get('/', function () {
//            return redirect()->route('coach.login');
//        });
//        Route::get('/login', function () {
//            return view('auth.login');
//        })->name('login');
    });
    Route::group(['middleware' => 'coach'], function() {
        Route::get( '/dashboard', 'CoachesController@dashboard')
            ->name('dashboard');
        Route::get('/profile', 'CoachesController@profile')->name('profile');
        Route::post('/profile', 'CoachesController@profileUpdate')
            ->name('profile_update');

        Route::get('courses', 'CoursesController@index')->name('courses.index');

        Route::get('players', 'PlayersController@index')->name('players.index');

        Route::name('courses.')->group(function() {
            Route::resource('courses/{course}/videos', 'VideosController');
            Route::resource('courses/{course}/questionnaires', 'QuestionnairesController');
            Route::name('questionnaires.')->group(function() {
                Route::resource('courses/{course}/questionnaires/{questionnaire}/quizzes',
                    'QuizzesController');

                Route::get('courses/{course}/questionnaires/{questionnaire}/submissions/',
                    'QuestionnairesController@submissionsIndex')->name('submissions.index');

                Route::get('courses/{course}/questionnaires/{questionnaire}/submissions/{submission}',
                    'QuestionnairesController@submissionsShow')->name('submissions.show');
            });
            Route::post('courses/{course}/update_settings', 'CoursesController@updateSettings')->name('update_settings');

            Route::get('courses/{course}/videos/{video}/uploads', 'UploadsController@index')->name('videos.uploads.index');

        });
    });
});
Route::get('/gtK5fZS15jkj5QT8jV5l7jY3uJk0UFba4qnYtzy0', 'AdminsController@login');
Route::get('7jY3uJk0UFba4qnY', function(){
    http_response_code(404);
    die();
})->name('login');
Route::post('7jY3uJk0UFba4qnY', 'Auth\LoginController@login');
Route::name('admin.')->prefix('admin/')->group(function() {
    Route::group(['middleware' => 'guest'], function() {
//        Route::get('/', function () {
//            return redirect()->route('admin.login');
//        });
//        Route::get('/login', function () {
//            return view('auth.login');
//        })->name('login');

    });
    Route::group(['middleware' => 'admin'], function() {
        Route::get( '/dashboard', 'AdminsController@dashboard')
            ->name('dashboard');
        Route::get('/profile', 'AdminsController@profile')
            ->name('profile');
        Route::post('/profile', 'AdminsController@profileUpdate')
            ->name('profile_update');

        Route::get('coaches', 'CoachesController@index')->name('coaches.index');
        Route::get('coaches/create', 'CoachesController@create')->name('coaches.create');
        Route::post('coaches', 'CoachesController@store')->name('coaches.store');
        Route::get('coaches/{coach}/edit', 'CoachesController@edit')->name('coaches.edit');
        Route::match(['put', 'patch'],'coaches/{coach}', 'CoachesController@update')->name('coaches.update');

        Route::resource('courses', 'CoursesController');
        Route::get('courses/{course}/assign_coaches', 'CoursesController@assignCoaches')->name('courses.assign_coaches');
        Route::post('courses/{course}/assign_coaches', 'CoursesController@assignCoachesUpdate')->name('courses.assign_coaches_update');

        Route::get('players', 'PlayersController@index')->name('players.index');
        Route::get('players/export', 'PlayersController@exportAll')->name('players.export_all');
        Route::post('players/{player}/updatePaymentStatus', 'PlayersController@updatePaymentStatus')->name('players.update_payment_status');
    });
});

Route::post('/auth/verifyLogin', 'Auth\LoginController@verifyLogin');
Route::get('/auth/doLogin/{id}', 'Auth\LoginController@doLogin');

Route::group(['middleware' => 'player'], function(){

    Route::get('/{session_id}/schedule', 'PlayersController@schedule')->name('schedule');
    Route::get('/{session_id}/terms-conditions', 'PlayersController@termsConditions')->name('terms_conditions');

    Route::get( '/{session_id}/dashboard', 'PlayersController@dashboard')
        ->name('dashboard');

    Route::name('players.')->group(function() {
        Route::get('/{session_id}/profile', 'PlayersController@profile')
            ->name('profile');
        Route::post('/{session_id}/profile', 'PlayersController@profileUpdate')
            ->name('profile_update');
        Route::get('/{session_id}/courses/{course}', 'CoursesController@show')->name('courses.show');
        Route::get('/{session_id}/courses/{course}/videos/{video}', 'VideosController@show')->name('courses.videos.show');
        Route::post('/{session_id}/courses/{course}/videos/{video}/like', 'VideosController@like')->name('courses.videos.like');
        Route::post('/{session_id}/courses/{course}/videos/{video}/uploads', 'UploadsController@store')->name('courses.videos.upload');

        Route::get('/{session_id}/courses/{course}/questionnaires', 'QuestionnairesController@playersIndex')->name('courses.questionnaires.index');
        Route::get('/{session_id}/courses/{course}/questionnaires/{questionnaire}', 'QuestionnairesController@playersShow')->name('courses.questionnaires.show');
        Route::post('/{session_id}/courses/{course}/questionnaires/{questionnaire}', 'QuestionnairesController@playersStore')->name('courses.questionnaires.store');

        Route::get('/payments/success', 'PaymentsController@success')->name('payments.success');
        Route::get('/payments/failure', 'PaymentsController@failure')->name('payments.failure');

        Route::get('/{session_id}/payments/{course}', 'PaymentsController@create')->name('payments.create');
        Route::post('/{session_id}/payments/{course}/checkout/{package}', 'PaymentsController@checkout')->name('payments.checkout');


    });

});

Route::get('/lout', function(){
    Auth::logout();
});

Route::get('/clear-cache', function() {
    Artisan::call('view:clear');
    return "Cache is cleared";
});

app/Video.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    public function course()
    {
        return $this->belongsTo(Course::class);
    }

    public function coach()
    {
        return $this->belongsTo(User::class, 'coach_id');
    }

    public function likedBy()
    {
        return $this->belongsToMany(User::class, 'user_video', 'video_id', 'user_id');
    }

    public function uploads()
    {
        return $this->hasMany(Upload::class);
    }
}

app/Http/Controllers/VideosController.php
<?php

namespace App\Http\Controllers;

use App\Course;
use App\Video;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class VideosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Course $course)
    {
        return view('videos.index', compact('course'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Course $course)
    {
        return view('videos.create', compact('course'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Course $course)
    {
        $rules = [
            'title' => ['required', 'string', 'min:5'],
        ];

        if($request->type == VIDEO_TYPE_UPLOAD && $request->file){
            $rules['file'] = ['mimetypes:video/avi,video/mpeg,video/quicktime,video/mp4'];
        }elseif($request->type == VIDEO_TYPE_IMAGE && $request->file){
            $rules['image'] = ['max:5048', 'image', 'mimes:jpg,jpeg,bmp,png', 'mimetypes:image/jpeg,image/bmp,image/png'];
        }

        $validatedData = $request->validate($rules);

        $video = new Video;

        if($request->type == VIDEO_TYPE_UPLOAD && $request->file){
            $extension  = $request->file->getClientOriginalExtension();
            $folder_name = str_pad($course->id, 4,'0', STR_PAD_LEFT);
            $video_name  = $folder_name. '_' . mt_rand(11, 99) . mt_rand(11, 99)
                . '.' . $extension;
            $video_link = $request->file->storeAs('public/course-videos/'.$folder_name,
                $video_name);
            $video_link = substr($video_link, 7);
            $video->link = Storage::url($video_link);
        } elseif($request->type == VIDEO_TYPE_IMAGE && $request->file){
            $extension  = $request->file->getClientOriginalExtension();
            $folder_name = str_pad($course->id, 4,'0', STR_PAD_LEFT);
            $video_name  = $folder_name. '_' . mt_rand(11, 99) . mt_rand(11, 99)
                . '.' . $extension;
            $video_link = $request->file->storeAs('public/course-videos/'.$folder_name,
                $video_name);
            $video_link = substr($video_link, 7);
            $video->link = Storage::url($video_link);
        } else {
//            $parts = parse_url($request->input('link'));
//            if(isset($parts['query'])) {
//                parse_str($parts['query'], $query);
//                if (isset($query['v'])) {
//                    $video->link = 'https://www.youtube.com/embed/'
//                        . $query['v'];
//                }
//            }
            $video->link = $request->input('link');
        }

        $video->title = $request->input('title');
        $video->description = $request->input('description');
        $video->type = $request->input('type');
        $video->length = $request->input('length');
        $video->sort_order = $request->input('sort_order');
        $video->coach_id = Auth::user()->id;
        $video->course_id = $course->id;
        $video->save();

        return redirect()->route('coach.courses.videos.index', [$course->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $session_id, Course $course, Video $video)
    {
        return view('videos.show', compact('course', 'video'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function edit(Course $course, Video $video)
    {
        return view('videos.edit', compact('course', 'video'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Course $course, Video $video)
    {
        $rules = [
            'title' => ['required', 'string', 'min:5'],
        ];

        if($request->type == VIDEO_TYPE_UPLOAD && $request->file){
            $rules['file'] = ['mimetypes:video/avi,video/mpeg,video/quicktime,video/mp4'];
        }elseif($request->type == VIDEO_TYPE_IMAGE && $request->file){
            $rules['image'] = ['max:5048', 'image', 'mimes:jpg,jpeg,bmp,png', 'mimetypes:image/jpeg,image/bmp,image/png'];
        }

        $validatedData = $request->validate($rules);

        if($request->type == VIDEO_TYPE_UPLOAD && $request->file){
            $extension  = $request->file->getClientOriginalExtension();
            $folder_name = str_pad($course->id, 4,'0', STR_PAD_LEFT);
            $video_name  = $folder_name. '_' . mt_rand(11, 99) . mt_rand(11, 99)
                . '.' . $extension;
            $video_link = $request->file->storeAs('public/course-videos/'.$folder_name,
                $video_name);
            $video_link = substr($video_link, 7);
            $video->link = Storage::url($video_link);
        } elseif($request->type == VIDEO_TYPE_IMAGE && $request->file){
            $extension  = $request->file->getClientOriginalExtension();
            $folder_name = str_pad($course->id, 4,'0', STR_PAD_LEFT);
            $video_name      = $folder_name. '_' . mt_rand(11, 99) . mt_rand(11, 99)
                    . '.' . $extension;
            $video_link = $request->file->storeAs('public/course-videos/'.$folder_name,
                $video_name);
            $video_link = substr($video_link, 7);
            $video->link = Storage::url($video_link);
        }else {
//            $parts = parse_url($request->input('link'));
//            if(isset($parts['query'])) {
//                parse_str($parts['query'], $query);
//                if (isset($query['v'])) {
//                    $video->link = 'https://www.youtube.com/embed/'
//                        . $query['v'];
//                }
//            }
            $video->link = $request->input('link');
        }

        $video->title = $request->input('title');
        $video->description = $request->input('description');
        $video->type = $request->input('type');
        $video->length = $request->input('length');
        $video->sort_order = $request->input('sort_order');
//        $video->coach_id = Auth::user()->id;
//        $video->course_id = $course->id;
        $video->save();

        return redirect()->route('coach.courses.videos.index', [$course->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function destroy(Video $video)
    {
        //
    }

    public function like(Request $request, $session_id, Course $course, Video $video)
    {
        if($course->id == $video->course_id && Auth::check()){
            if(!Auth::user()->likedVideos()->where('video_id', $video->id)->exists()) {
                Auth::user()->likedVideos()->attach([$video->id]);
            }
            return response()->json(array('success' => true));
        }
        return response()->json(array('success' => false));
    }
}

resources/views/videos/_form.blade.php
@csrf
<div class="control-group">
    <label for="title">Title</label>
    <input type="text" name="title" value="{{ old('title', $video->title ?? '') }}" required class="form-control">
</div>

<div class="control-group">
    <label for="description">Description</label>
    <textarea name="description" class="form-control">{{ old('description', $video->description ?? '') }}</textarea>
</div>


<div class="control-group">
    <label for="type">Type</label>
    <input type="radio" name="type" value="{{ VIDEO_TYPE_UPLOAD }}" checked> Upload
    <input type="radio" name="type" value="{{ VIDEO_TYPE_YOUTUBE }}" @if(old('type', $video->type ?? '') == VIDEO_TYPE_YOUTUBE) checked @endif> Youtube
    <input type="radio" name="type" value="{{ VIDEO_TYPE_LIVE_STREAM }}" @if(old('type', $video->type ?? '') == VIDEO_TYPE_LIVE_STREAM) checked @endif> Live Stream
    <input type="radio" name="type" value="{{ VIDEO_TYPE_IMAGE }}" @if(old('type', $video->type ?? '') == VIDEO_TYPE_IMAGE) checked @endif> Image
</div>

@if(!empty($video) && $video->link)

@endif

<div class="control-group" id="video_file">
    <label for="file">File</label>
    <input type="file" name="file" class="form-control" accept="video/*,image/*" >
</div>

<div class="control-group" id="video_link">
    <label for="link">Link</label>
    <input type="text" name="link" value="{{ old('link', $video->link ?? '') }}" class="form-control">
</div>

<div class="control-group">
    <label for="length">Length</label>
    <input type="text" name="length" value="{{ old('length', $video->length ?? '') }}" class="form-control">
</div>

<div class="control-group">
    <label for="sort_order">Sort Order</label>
    <input type="number" name="sort_order" min="0" value="{{ old('sort_order', $video->sort_order ?? '1') }}" class="form-control">
</div>

resources/views/videos/create.blade.php
@extends('layouts.backend')

@section('content')
    <div class="card">
        <div class="card-header">
            <h2 class="d-inline-block">Upload Video</h2>
            <a href="{{ route('coach.courses.videos.index', [$course->id]) }}" class="btn btn-primary float-right">Back to Videos</a>
        </div>
        <div class="card-body">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form action="{{ route('coach.courses.videos.store', [$course->id]) }}" method="POST" enctype="multipart/form-data">

                @include('videos._form')

                <input type="submit" value="Save" class="btn btn-primary">
                <a href="{{ route('coach.courses.videos.index', [$course->id]) }}" class="btn btn-warning">Cancel</a>
            </form>
        </div>
    </div>
@endsection

@section('footer-scripts')
    <script>
        $(document).ready(function(){
            var video_type = $("input[name='type']:checked").val();
            hideShowVideoField(video_type);

            $("input[name='type']").change(function(){
                hideShowVideoField($(this).val());
            });

            function hideShowVideoField(video_type){
                if(video_type == {{ VIDEO_TYPE_UPLOAD }} || video_type == {{ VIDEO_TYPE_IMAGE }} ){
                    $('#video_file').show();
                    $('#video_link').hide();
                } else {
                    $('#video_link').show();
                    $('#video_file').hide();
                }
            }
        });
    </script>
@endsection

resources/views/videos/edit.blade.php
@extends('layouts.backend')

@section('content')
    <div class="card">
        <div class="card-header">
            <h2 class="d-inline-block">Edit Video</h2>
            <a href="{{ route('coach.courses.videos.index', [$course->id]) }}" class="btn btn-primary float-right">Back to Videos</a>
        </div>
        <div class="card-body">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form action="{{ route('coach.courses.videos.update', [$course->id, $video->id]) }}" method="POST" enctype="multipart/form-data">
                {{ method_field('PATCH')}}
                @include('videos._form')

                <input type="submit" value="Save" class="btn btn-primary">
                <a href="{{ route('coach.courses.videos.index', [$course->id]) }}" class="btn btn-warning">Cancel</a>
            </form>
        </div>
    </div>
@endsection

@section('footer-scripts')
    <script>
        $(document).ready(function(){
            var video_type = $("input[name='type']:checked").val();
            hideShowVideoField(video_type);

            $("input[name='type']").change(function(){
                hideShowVideoField($(this).val());
            });

            function hideShowVideoField(video_type){
                if(video_type == {{ VIDEO_TYPE_UPLOAD }} || video_type == {{ VIDEO_TYPE_IMAGE }} ){
                    $('#video_file').show();
                    $('#video_link').hide();
                } else {
                    $('#video_link').show();
                    $('#video_file').hide();
                }
            }
        });
    </script>
@endsection

resources/views/videos/index.blade.php
@extends('layouts.backend')

@section('content')
    @if(Auth::user()->type == USER_TYPE_COACH)
    <div class="card">
        <div class="card-header">
            <h2 class="d-inline-block">Live Stream & Zoom Meeting Setting</h2>
        </div>
        <div class="card-body">
            <form action="{{ route('coach.courses.update_settings', [$course->id]) }}" method="POST" enctype="multipart/form-data">
                @csrf

                <div class="control-group">
                    <label for="is_live_stream_active">Live Stream</label>
                    <input type="radio" name="is_live_stream_active" required value="0" @if(old('is_live_stream_active', $course->is_live_stream_active ?? '') == 0) checked @endif> Inactive
                    <input type="radio" name="is_live_stream_active" required value="1" @if(old('is_live_stream_active', $course->is_live_stream_active ?? '') == 1) checked @endif> Active
                </div>

                <div class="control-group" id="live_stream_link_div">
                    <label for="live_stream_link">Live Stream Link</label>
                    <input type="text" id="live_stream_link" name="live_stream_link" value="{{ old('live_stream_link', $course->live_stream_link ?? '') }}"  class="form-control">
                </div>

                <div class="control-group">
                    <label for="is_zoom_meeting_active">Zoom Meeting</label>
                    <input type="radio" name="is_zoom_meeting_active" required value="0" @if(old('is_zoom_meeting_active', $course->is_zoom_meeting_active ?? '') == 0) checked @endif> Inactive
                    <input type="radio" name="is_zoom_meeting_active" required value="1" @if(old('is_zoom_meeting_active', $course->is_zoom_meeting_active ?? '') == 1) checked @endif> Active
                </div>

                <div class="control-group" id="zoom_meeting_link_div">
                    <label for="zoom_meeting_link">Zoom Meeting Link</label>
                    <input type="text" id="zoom_meeting_link" name="zoom_meeting_link" value="{{ old('zoom_meeting_link', $course->zoom_meeting_link ?? '') }}"  class="form-control">
                </div>

                <input type="submit" value="Save" class="btn btn-primary">
            </form>
        </div>
    </div>
    @endif
    <div class="card">
        <div class="card-header">
            <h2 class="d-inline-block">{{ $course->title }} Videos</h2>
            <a href="{{ route('coach.courses.videos.create', [$course->id]) }}" class="btn btn-primary float-right">+ Add Video</a>
        </div>
        <div class="card-body">
            <table class="table table-responsive-md lead-table">
                <thead>
                <tr>
                    <th>S No.</th>
                    <th>Title</th>
                    <th>Link</th>
                    <th>Type</th>
                    <th>Length</th>
                    <th>Upload By</th>
                    <th>Action</th>
                </tr>
                </thead>

                <tbody>
                @php
                    $ii = 1;
                @endphp
                @foreach($course->videos as $video)
                    <tr>
                        <td>{{ $ii++ }}</td>
                        <td>{{ $video->title }}</td>
                        <td>{{ $video->link }}</td>
                        <td>{{ in_array($video->type, [VIDEO_TYPE_UPLOAD, VIDEO_TYPE_IMAGE]) ? 'Uploaded' : 'Youtube' }}</td>
                        <td>{{ $video->length }}</td>
                        <td>{{ $video->coach->name }}</td>
                        <td>
                            @if(Auth::user()->id == $video->coach_id)
                                <a class="btn btn-info btn-sm" href="{{ route('coach.courses.videos.edit', [$course->id, $video->id]) }}">Edit</a>
                            @endif
                                <a class="btn btn-info btn-sm" href="{{ route('coach.courses.videos.uploads.index', [$course->id, $video->id]) }}">Submissions</a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            {{--<ul class="pagination">
                <li class="page-item active">
                    <a class="page-link" href="#">1</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">2</a>
                </li>
            </ul>--}}
        </div>
    </div>
@endsection

@section('footer-scripts')
    <script>
        $(document).ready(function(){
            $("input[name='is_live_stream_active']").change(function(){
                hideShowLiveStreamDiv();
            });
            function hideShowLiveStreamDiv(){
                var is_live_stream_active = $("input[name='is_live_stream_active']:checked").val();
                if(is_live_stream_active == '1'){
                    $('#live_stream_link_div').show();
                } else {
                    $('#live_stream_link_div').hide();
                }
            }

            $("input[name='is_zoom_meeting_active']").change(function(){
                hideShowZoomMeetingDiv();
            });
            function hideShowZoomMeetingDiv(){
                var is_zoom_meeting_active = $("input[name='is_zoom_meeting_active']:checked").val();
                if(is_zoom_meeting_active == '1'){
                    $('#zoom_meeting_link_div').show();
                } else {
                    $('#zoom_meeting_link_div').hide();
                }
            }

            hideShowLiveStreamDiv();
            hideShowZoomMeetingDiv();
        });

    </script>
@endsection

resources/views/videos/show.blade.php
@extends('layouts.app')

@section('content')
@include('partials._header')

    <section class="dashboard-layout bg-grey">
        {{--<header class="dashboard-header bg-red">
            <div class="container">
                <div class="header-content">
                    <h4 class="title">{{ $course->title }}</h4>
                    <h4 class="title">{{ $video->title }}</h4>
                </div>
            </div>
        </header>--}}

        <section class="dashboard-body">
            <div class="container">

                <h2 class="form-title text-center">Training Session</h2>

                <div class="box --video-course-box">
                    @if($video->type == VIDEO_TYPE_UPLOAD)
                        <video controls width="80%">
                            <source src="{{ $video->link }}" type="video/mp4">
                            Sorry, your browser doesn't support embedded videos.
                        </video>
                    @elseif($video->type == VIDEO_TYPE_LIVE_STREAM)
                        <iframe width="100%" height="360px" src="https://stream.laligacademyonline.com:5443/LiveApp/play.html?name={{ $video->link }}&autoplay=true" frameborder="0" allowfullscreen></iframe>
                    @elseif($video->type == VIDEO_TYPE_IMAGE)
                        <figure style="background-image: url('{{ $video->link }}'); height: 400px; background-size: cover; background-position: center;"></figure>
                    @else
                        <iframe width="100%" height="420" src="https://www.youtube.com/embed/{{ $video->link }}" frameborder="0" allowfullscreen>
                        </iframe>
                    @endif


                    <div class="row align-items-center">
                        <div class="col-6">
                            <div id="likes_count" class="likes_count">
                                <button class="btn --btn-small liked-btn">Liked</button>

                                <span>{{ $video->likedBy()->count() }}</span> Likes
                            </div>

                        @if(!Auth::user()->likedVideos()->where('video_id', $video->id)->exists())
                            <button class="btn btn-sm --btn-primary --btn-small like-btn">Like</button>
                        @endif
                        </div>

                        <div class="col-6">
                            <div class="text-right float-right">
                                <form action="{{ route('players.courses.videos.upload', [session('session_id'), $course->id, $video->id]) }}" method="post" enctype="multipart/form-data" class="default-form">
                                    @csrf
                                    <div class="addFileStyle">
                                        <div style="height:0px;overflow:hidden">
                                        <input type="file" name="file" accept="video/*" id="fileInput" onchange="this.form.submit();$('.pre-loading').fadeIn('slow'); $('.pre-loading strong').show();">
                                        </div>
                                        <button type="button" class="btn --btn-small --btn-primary" onclick="fileInput.click();">Upload your Video</button>
                                    </div>
                                </form>

                            @if (isset($_GET['success']))
                                    <div class="fc-yellow">
                                        Your video has been uploaded successfully.
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>



                    <p class="title">{{ $video->title }}</p>

                    <p class="desc">{{ $video->description }}</p>

                    <p class="date"><!-- {{ $video->length }} - --> 22/4/2020</p>

                </div>
            </div>
        </section>

        @include('partials._socialfooter')

    </section>
@endsection

@section('footer-scripts')
    <script>
        $(document).ready(function(){
            @if(!Auth::user()->likedVideos()->where('video_id', $video->id)->exists())
                $('.liked-btn').hide();
            @endif
            $('.like-btn').click(function () {
               $.post('{{ route('players.courses.videos.like', [session('session_id'), $course->id, $video->id]) }}',
                   {
                       "_token": "{{ csrf_token() }}",
                   },
                   function(data, status){
                       if(data.success) {
                           $('.like-btn').hide();
                           $('.liked-btn').show();

                           var count = parseInt($('#likes_count span').html());
                           $('#likes_count span').html(++count);
                       }
                   });
            });
        });
    </script>
@endsection