routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::group(['middleware' => 'guest'], function() {
    Route::get('/', function(){
        return redirect('https://ae.laligacademy.com/online/');
    });

//});


//Auth::routes(['verify' => true]);
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('login', function(){
    return redirect('https://ae.laligacademy.com/online/login/');
});

//Route::get('/live-stream', function(){
//    return view('players.live_stream');
//});
Route::get('/redirectToUserHome', 'Auth\LoginController@redirectToUserHome');


Route::get('payments/redirectTo/{action}', 'PaymentsController@redirectRoutes');
Route::post('payments/redirectTo/{action}', 'PaymentsController@redirectRoutes')->name('players.payments.redirect_routes');

Route::name('coach.')->prefix('coach/')->group(function() {
    Route::group(['middleware' => 'guest'], function() {
//        Route::get('/', function () {
//            return redirect()->route('coach.login');
//        });
//        Route::get('/login', function () {
//            return view('auth.login');
//        })->name('login');
    });
    Route::group(['middleware' => 'coach'], function() {
        Route::get( '/dashboard', 'CoachesController@dashboard')
            ->name('dashboard');
        Route::get('/profile', 'CoachesController@profile')->name('profile');
        Route::post('/profile', 'CoachesController@profileUpdate')
            ->name('profile_update');

        Route::get('courses', 'CoursesController@index')->name('courses.index');

        Route::get('players', 'PlayersController@index')->name('players.index');

        Route::name('courses.')->group(function() {
            Route::resource('courses/{course}/videos', 'VideosController');
            Route::resource('courses/{course}/questionnaires', 'QuestionnairesController');
            Route::name('questionnaires.')->group(function() {
                Route::resource('courses/{course}/questionnaires/{questionnaire}/quizzes',
                    'QuizzesController');

                Route::get('courses/{course}/questionnaires/{questionnaire}/submissions/',
                    'QuestionnairesController@submissionsIndex')->name('submissions.index');

                Route::get('courses/{course}/questionnaires/{questionnaire}/submissions/{submission}',
                    'QuestionnairesController@submissionsShow')->name('submissions.show');
            });
            Route::post('courses/{course}/update_settings', 'CoursesController@updateSettings')->name('update_settings');

            Route::get('courses/{course}/videos/{video}/uploads', 'UploadsController@index')->name('videos.uploads.index');

        });
    });
});
Route::get('/gtK5fZS15jkj5QT8jV5l7jY3uJk0UFba4qnYtzy0', 'AdminsController@login');
Route::get('7jY3uJk0UFba4qnY', function(){
    http_response_code(404);
    die();
})->name('login');
Route::post('7jY3uJk0UFba4qnY', 'Auth\LoginController@login');
Route::name('admin.')->prefix('admin/')->group(function() {
    Route::group(['middleware' => 'guest'], function() {
//        Route::get('/', function () {
//            return redirect()->route('admin.login');
//        });
//        Route::get('/login', function () {
//            return view('auth.login');
//        })->name('login');

    });
    Route::group(['middleware' => 'admin'], function() {
        Route::get( '/dashboard', 'AdminsController@dashboard')
            ->name('dashboard');
        Route::get('/profile', 'AdminsController@profile')
            ->name('profile');
        Route::post('/profile', 'AdminsController@profileUpdate')
            ->name('profile_update');

        Route::get('coaches', 'CoachesController@index')->name('coaches.index');
        Route::get('coaches/create', 'CoachesController@create')->name('coaches.create');
        Route::post('coaches', 'CoachesController@store')->name('coaches.store');
        Route::get('coaches/{coach}/edit', 'CoachesController@edit')->name('coaches.edit');
        Route::match(['put', 'patch'],'coaches/{coach}', 'CoachesController@update')->name('coaches.update');

        Route::resource('courses', 'CoursesController');
        Route::get('courses/{course}/assign_coaches', 'CoursesController@assignCoaches')->name('courses.assign_coaches');
        Route::post('courses/{course}/assign_coaches', 'CoursesController@assignCoachesUpdate')->name('courses.assign_coaches_update');

        Route::get('players', 'PlayersController@index')->name('players.index');
        Route::get('players/export', 'PlayersController@exportAll')->name('players.export_all');
        Route::post('players/{player}/updatePaymentStatus', 'PlayersController@updatePaymentStatus')->name('players.update_payment_status');
    });
});

Route::post('/auth/verifyLogin', 'Auth\LoginController@verifyLogin');
Route::get('/auth/doLogin/{id}', 'Auth\LoginController@doLogin');

Route::group(['middleware' => 'player'], function(){

    Route::get('/{session_id}/schedule', 'PlayersController@schedule')->name('schedule');
    Route::get('/{session_id}/terms-conditions', 'PlayersController@termsConditions')->name('terms_conditions');

    Route::get( '/{session_id}/dashboard', 'PlayersController@dashboard')
        ->name('dashboard');

    Route::name('players.')->group(function() {
        Route::get('/{session_id}/profile', 'PlayersController@profile')
            ->name('profile');
        Route::post('/{session_id}/profile', 'PlayersController@profileUpdate')
            ->name('profile_update');
        Route::get('/{session_id}/courses/{course}', 'CoursesController@show')->name('courses.show');
        Route::get('/{session_id}/courses/{course}/videos/{video}', 'VideosController@show')->name('courses.videos.show');
        Route::post('/{session_id}/courses/{course}/videos/{video}/like', 'VideosController@like')->name('courses.videos.like');
        Route::post('/{session_id}/courses/{course}/videos/{video}/uploads', 'UploadsController@store')->name('courses.videos.upload');

        Route::get('/{session_id}/courses/{course}/questionnaires', 'QuestionnairesController@playersIndex')->name('courses.questionnaires.index');
        Route::get('/{session_id}/courses/{course}/questionnaires/{questionnaire}', 'QuestionnairesController@playersShow')->name('courses.questionnaires.show');
        Route::post('/{session_id}/courses/{course}/questionnaires/{questionnaire}', 'QuestionnairesController@playersStore')->name('courses.questionnaires.store');

        Route::get('/payments/success', 'PaymentsController@success')->name('payments.success');
        Route::get('/payments/failure', 'PaymentsController@failure')->name('payments.failure');

        Route::get('/{session_id}/payments/{course}', 'PaymentsController@create')->name('payments.create');
        Route::post('/{session_id}/payments/{course}/checkout/{package}', 'PaymentsController@checkout')->name('payments.checkout');


    });

});

Route::get('/lout', function(){
    Auth::logout();
});

Route::get('/clear-cache', function() {
    Artisan::call('view:clear');
    return "Cache is cleared";
});

app/Questionnaire.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Questionnaire extends Model
{
    use SoftDeletes;

    public function coach()
    {
        return $this->belongsTo(User::class, 'coach_id');
    }

    public function quizzes()
    {
        return $this->hasMany(Quiz::class);
    }
}

app/Http/Controllers/QuestionnairesController.php
<?php

namespace App\Http\Controllers;

use App\Course;
use App\Questionnaire;
use App\QuestionnaireSubmission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class QuestionnairesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Course $course)
    {
        return view('questionnaires.index', compact('course'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Course $course)
    {
        return view('questionnaires.create', compact('course'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Course $course)
    {
        $questionnaire = new Questionnaire();
        $questionnaire->title = $request->title;
        $questionnaire->description = $request->description;
        $questionnaire->coach_id = Auth::user()->id;
        $questionnaire->course_id = $course->id;
        $questionnaire->save();

        return redirect()->route('coach.courses.questionnaires.index', compact('course'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Questionnaire  $questionnaire
     * @return \Illuminate\Http\Response
     */
    public function show(Questionnaire $questionnaire)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Questionnaire  $questionnaire
     * @return \Illuminate\Http\Response
     */
    public function edit(Course $course, Questionnaire $questionnaire)
    {
        return view('questionnaires.edit', compact('course', 'questionnaire'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Questionnaire  $questionnaire
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Course $course,  Questionnaire $questionnaire)
    {
        $questionnaire->title = $request->title;
        $questionnaire->description = $request->description;
        $questionnaire->save();

        return redirect()->route('coach.courses.questionnaires.index', compact('course'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Questionnaire  $questionnaire
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Course $course, Questionnaire $questionnaire)
    {
        $questionnaire->delete();
        $questionnaire->quizzes()->delete();
        return redirect()->route('coach.courses.questionnaires.index', compact('course'));
    }

    public function playersIndex($session_id, Course $course)
    {
        return view('questionnaires.players_index', compact('course'));
    }

    public function playersShow($session_id, Course $course, Questionnaire $questionnaire)
    {
        $submission = QuestionnaireSubmission::where('questionnaire_id', $questionnaire->id)
                        ->where('user_id', Auth::user()->id)->first();
        $answers = false;
        if(!$submission){
            $submission = false;
        } else {
            $answers = json_decode($submission->answers,true);
        }
        return view('questionnaires.players_show', compact('course', 'questionnaire', 'submission', 'answers'));
    }

    function playersStore(Request $request, $session_id, Course $course, Questionnaire $questionnaire)
    {
        $submission = QuestionnaireSubmission::where('questionnaire_id',
            $questionnaire->id)->where('user_id', Auth::user()->id)->first();

        if ( ! $submission) {
            $answers = [];
            foreach ($questionnaire->quizzes as $quiz) {
                $answers['quiz_id_' . $quiz->id] = $_POST['quiz_id_' . $quiz->id];
                if(isset($_POST['descriptive_field_' . $quiz->id])){
                    $answers['descriptive_field_' . $quiz->id] = $_POST['descriptive_field_' . $quiz->id];
                }
            }

            $submission                   = new QuestionnaireSubmission;
            $submission->answers          = json_encode($answers);
            $submission->user_id          = Auth::user()->id;
            $submission->questionnaire_id = $questionnaire->id;
            $submission->save();
        }

        return redirect()->route('players.courses.questionnaires.show', [session('session_id'), $course, $questionnaire]);
    }

    public function submissionsIndex(Request $request, Course $course, Questionnaire $questionnaire)
    {
        $submissions = QuestionnaireSubmission::where('questionnaire_id',$questionnaire->id)->get();
        $total_quizzes = $questionnaire->quizzes->count();

        return view('questionnaires.submissions_index', compact('submissions', 'course', 'questionnaire', 'total_quizzes'));
    }

    public function submissionsShow(Request $request, Course $course, Questionnaire $questionnaire, QuestionnaireSubmission $submission)
    {
        $answers = json_decode($submission->answers,true);
        return view('questionnaires.players_show', compact('course', 'questionnaire', 'submission', 'answers'));
    }
}

resources/views/questionnaires/_form.blade.php
@csrf
<div class="control-group">
    <label for="title">Title</label>
    <input type="text" name="title" value="{{ old('title', $questionnaire->title ?? '') }}" required class="form-control">
</div>

<div class="control-group">
    <label for="description">Description</label>
    <textarea name="description" class="form-control">{{ old('description', $questionnaire->description ?? '') }}</textarea>
</div>

resources/views/questionnaires/create.blade.php
@extends('layouts.backend')

@section('content')
    <div class="card">
        <div class="card-header">
            <h2 class="d-inline-block">Create Questionnaire</h2>
            <a href="{{ route('coach.courses.questionnaires.index', [$course->id]) }}" class="btn btn-primary float-right">Back to Questionnaires</a>
        </div>
        <div class="card-body">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form action="{{ route('coach.courses.questionnaires.store', [$course->id]) }}" method="POST">

                @include('questionnaires._form')

                <input type="submit" value="Save" class="btn btn-primary">
                <a href="{{ route('coach.courses.questionnaires.index', [$course->id]) }}" class="btn btn-warning">Cancel</a>
            </form>
        </div>
    </div>
@endsection

@section('footer-scripts')
    <script>
        $(document).ready(function(){
            var video_type = $("input[name='type']:checked").val();
            hideShowVideoField(video_type);

            $("input[name='type']").change(function(){
                hideShowVideoField($(this).val());
            });

            function hideShowVideoField(video_type){
                if(video_type == {{ VIDEO_TYPE_UPLOAD }}){
                    $('#video_file').show();
                    $('#video_link').hide();
                } else {
                    $('#video_link').show();
                    $('#video_file').hide();
                }
            }
        });
    </script>
@endsection

resources/views/questionnaires/edit.blade.php
@extends('layouts.backend')

@section('content')
    <div class="card">
        <div class="card-header">
            <h2 class="d-inline-block">Edit Questionnaire</h2>
            <a href="{{ route('coach.courses.questionnaires.index', [$course->id]) }}" class="btn btn-primary float-right">Back to Questionnaires</a>
        </div>
        <div class="card-body">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form action="{{ route('coach.courses.questionnaires.update', [$course->id, $questionnaire->id]) }}" method="POST">
                {{ method_field('PATCH')}}
                @include('questionnaires._form')

                <input type="submit" value="Save" class="btn btn-primary">
                <a href="{{ route('coach.courses.questionnaires.index', [$course->id]) }}" class="btn btn-warning">Cancel</a>
            </form>
        </div>
    </div>
@endsection

@section('footer-scripts')
    <script>
        $(document).ready(function(){
        });
    </script>
@endsection

resources/views/questionnaires/index.blade.php
@extends('layouts.backend')

@section('content')
    <div class="card">
        <div class="card-header">
            <h2 class="d-inline-block">{{ $course->title }} - Questionnaires</h2>
            <a href="{{ route('coach.courses.questionnaires.create', [$course->id]) }}" class="btn btn-primary float-right">+ Add Questionnaire</a>
        </div>
        <div class="card-body">
            <table class="table table-responsive-md lead-table">
                <thead>
                <tr>
                    <th>S No.</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Created By</th>
                    <th>Created At</th>
                    <th>Action</th>
                </tr>
                </thead>

                <tbody>
                @php
                    $ii = 1;
                @endphp
                @foreach($course->questionnaires as $questionnaire)
                    <tr>
                        <td>{{ $ii++ }}</td>
                        <td>{{ $questionnaire->title }}</td>
                        <td>{{ $questionnaire->description }}</td>
                        <td>{{ $questionnaire->coach->name }}</td>
                        <td>{{ $questionnaire->created_at }}</td>
                        <td>
                            @if(Auth::user()->id == $questionnaire->coach_id)
                                <a class="btn btn-info btn-sm" href="{{ route('coach.courses.questionnaires.edit', [$course->id, $questionnaire->id]) }}">Edit</a>
                                <a class="btn --btn-primary btn-sm deleteItem" data-delete-id="{{ $questionnaire->id }}" href="#">Delete</a>
                            @endif
                                <a class="btn btn-info btn-sm" href="{{ route('coach.courses.questionnaires.submissions.index', [$course->id, $questionnaire->id]) }}">Submissions</a>
                                <a class="btn btn-info btn-sm" href="{{ route('coach.courses.questionnaires.quizzes.index', [$course->id, $questionnaire->id]) }}">Quizzes</a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            {{--<ul class="pagination">
                <li class="page-item active">
                    <a class="page-link" href="#">1</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">2</a>
                </li>
            </ul>--}}
        </div>
    </div>
    <form action="" id="deleteForm" method="POST" >
        {{ method_field('DELETE')}}
        @csrf
    </form>
@endsection

@section('footer-scripts')
    <script>
        var deleteResourceUrl = '{{ url()->current() }}';
        $(document).ready(function () {

            $('.deleteItem').click(function (e) {
                e.preventDefault();
                var deleteId = parseInt($(this).data('deleteId'));

                $('#deleteForm').attr('action', deleteResourceUrl + '/' + deleteId);

                if (confirm('Are you sure?')) {
                    $('#deleteForm').submit();
                }
            });

        });
    </script>
@endsection

resources/views/questionnaires/players_index.blade.php
@extends('layouts.app')

@section('content')
    @include('partials._header')

    <section class="dashboard-layout bg-grey">

        <section class="dashboard-body">
            <div class="container">
                <h2 class="form-title">{{ $course->title }} - Questionnaires</h2>
                @forelse($course->questionnaires as $questionnaire)
                <div class="box --question-box">
                    <div class="row align-items-center">
                        <div class="col-md-8">
                            <h4 class="title">{{ $questionnaire->title }}</h4>
                            <p class="desc">{{ $questionnaire->description }}</p>
                        </div>

                        <div class="col-md-4">
                            <div class="text-right">
                                <a href="{{ route('players.courses.questionnaires.show', [session('session_id'), $course->id, $questionnaire->id]) }}" class="btn --btn-primary">Take the Quiz</a>
                            </div>
                        </div>
                        </div>
                    </div>
                @empty
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <p>No Questionnaires.</p>
                        </div>
                    </div>
                @endforelse
            </div>
        </section>

        @include('partials._socialfooter')

    </section>
@endsection

@section('footer-scripts')
    <script>
        $(document).ready(function(){
        });
    </script>
@endsection

resources/views/questionnaires/players_show.blade.php
@extends('layouts.app')

@section('content')
    @include('partials._header')

    <section class="dashboard-layout bg-grey">

        <section class="dashboard-body">
            <div class="container">
                <h2 class="form-title">{{ $questionnaire->title }}</h2>
                @if($submission)
                <h4 class="mb-40">You Scored <span class="fc-yellow">{{ $submission->getScore() }}</span> out of <span class="fc-red">{{ $questionnaire->quizzes->count() }}</span></h4>
                @endif
                <form id="quiz_form" action="{{ route('players.courses.questionnaires.store', [session('session_id'), $questionnaire->course_id, $questionnaire->id]) }}" method="POST">
                    @csrf
                    @foreach($questionnaire->quizzes as $quiz)
                    <div class="box --quiz-box">
                        @if($quiz->media_type != 0 && $quiz->media)
                            @if($quiz->media_type == MEDIA_TYPE_IMAGE)
                                <img src="{{ $quiz->media }}" alt="*" style="max-width: 200px; max-height: 150px">
                            @elseif($quiz->media_type == MEDIA_TYPE_VIDEO)
                                <video controls width="80%">
                                    <source src="{{ $quiz->media }}" type="video/mp4">
                                    Sorry, your browser doesn't support embedded videos.
                                </video>
                            @endif
                            <br><br>
                        @endif
                        <p class="title">{{ $quiz->question }}</p>
                        @if($quiz->type == QUIZ_TYPE_MCQS)
                            @php
                                $ii = 0;
                            @endphp
                            @foreach(json_decode($quiz->options) as $option)
                                @if(!empty($option))
                                <div class="option-box">
                                    <input type="radio" class="quiz_radio" name="quiz_id_{{ $quiz->id }}" value="{{ ++$ii }}" @if($submission && $quiz->answer == $ii) checked @endif>
                                    <span class="label {{ $ii }}
                                    @if($submission && isset($answers['quiz_id_'.$quiz->id]) && $answers['quiz_id_'.$quiz->id] == $ii && $quiz->answer != $answers['quiz_id_'.$quiz->id])
                                        bg-red
                                    @endif
                                    ">{{ $option }}</span>
                                </div>
                                @endif
                            @endforeach
                        @else
                            <div class="option-box">
                                <input type="radio" class="quiz_radio" name="quiz_id_{{ $quiz->id }}" value="1" @if($submission && $quiz->answer == 1) checked @endif>
                                <span class="label
                                @if($submission && isset($answers['quiz_id_'.$quiz->id]) && $answers['quiz_id_'.$quiz->id] == 1 && $quiz->answer != $answers['quiz_id_'.$quiz->id])
                                    bg-red
                                @endif
                                ">True</span>
                            </div>
                            <div class="option-box">
                                <input type="radio" class="quiz_radio" name="quiz_id_{{ $quiz->id }}" value="0" @if($submission && $quiz->answer == 0) checked @endif>
                                <span class="label
                                @if($submission && isset($answers['quiz_id_'.$quiz->id]) && $answers['quiz_id_'.$quiz->id] == 0 && $quiz->answer != $answers['quiz_id_'.$quiz->id])
                                    bg-red
                                @endif
                                ">False</span>
                            </div>
                        @endif
                        @if($quiz->active_descriptive_field)
                                <textarea name="descriptive_field_{{ $quiz->id }}" id="descriptive_field_{{ $quiz->id }}" cols="30" rows="10">{{ $answers['descriptive_field_'.$quiz->id] ?? '' }}</textarea>
                        @endif
                    </div>
                    @endforeach
                    @if(!$submission)
                    <input type="button" class="btn --btn-submit" value="Submit">
                    @endif
                </form>
            </div>
        </section>

        @include('partials._socialfooter')

    </section>
@endsection

@section('footer-scripts')
    <script>
        $(document).ready(function(){
            $('.--btn-submit').click(function(){
                if($('input[class=quiz_radio]:checked').length == $('.box.--quiz-box p.title').length){
                    // Confirmation Box
                    if (confirm('Are you sure to submit the quiz?')) {
                        $('#quiz_form').submit();
                    }
                } else {
                    alert('Kindly select answers for all questions.');
                }
            });

            @if($submission)
            $('.box.--quiz-box input[type=radio]').attr('disabled','disabled');
            @endif
        });
    </script>
@endsection

resources/views/questionnaires/submissions_index.blade.php
@extends('layouts.backend')

@section('content')
    <div class="card">
        <div class="card-header">
            <h2 class="d-inline-block">{{ $course->title }} - {{ $questionnaire->title }} - Submissions</h2>
        </div>
        <div class="card-body">
            <table class="table table-responsive-md lead-table">
                <thead>
                <tr>
                    <th>S No.</th>
                    <th>Submitted By</th>
                    <th>Score</th>
                    <th>Created At</th>
                    <th>Actions</th>
                </tr>
                </thead>

                <tbody>
                @php
                    $ii = 1;
                @endphp
                @foreach($submissions as $submission)
                    <tr>
                        <td>{{ $ii++ }}</td>
                        <td>{{ $submission->user->name }}</td>
                        <td>{{ $submission->getScore() }}/{{ $total_quizzes }}</td>
                        <td>{{ $submission->created_at }}</td>
                        <td>
                            <a class="btn btn-info btn-sm" target="_blank" href="{{ route('coach.courses.questionnaires.submissions.show', [$course, $questionnaire, $submission]) }}">View</a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            {{--<ul class="pagination">
                <li class="page-item active">
                    <a class="page-link" href="#">1</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">2</a>
                </li>
            </ul>--}}
        </div>
    </div>
@endsection

@section('footer-scripts')
    <script>
        $(document).ready(function () {
        });
    </script>
@endsection