routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::group(['middleware' => 'guest'], function() {
    Route::get('/', function(){
        return redirect('https://ae.laligacademy.com/online/');
    });

//});


//Auth::routes(['verify' => true]);
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('login', function(){
    return redirect('https://ae.laligacademy.com/online/login/');
});

//Route::get('/live-stream', function(){
//    return view('players.live_stream');
//});
Route::get('/redirectToUserHome', 'Auth\LoginController@redirectToUserHome');


Route::get('payments/redirectTo/{action}', 'PaymentsController@redirectRoutes');
Route::post('payments/redirectTo/{action}', 'PaymentsController@redirectRoutes')->name('players.payments.redirect_routes');

Route::name('coach.')->prefix('coach/')->group(function() {
    Route::group(['middleware' => 'guest'], function() {
//        Route::get('/', function () {
//            return redirect()->route('coach.login');
//        });
//        Route::get('/login', function () {
//            return view('auth.login');
//        })->name('login');
    });
    Route::group(['middleware' => 'coach'], function() {
        Route::get( '/dashboard', 'CoachesController@dashboard')
            ->name('dashboard');
        Route::get('/profile', 'CoachesController@profile')->name('profile');
        Route::post('/profile', 'CoachesController@profileUpdate')
            ->name('profile_update');

        Route::get('courses', 'CoursesController@index')->name('courses.index');

        Route::get('players', 'PlayersController@index')->name('players.index');

        Route::name('courses.')->group(function() {
            Route::resource('courses/{course}/videos', 'VideosController');
            Route::resource('courses/{course}/questionnaires', 'QuestionnairesController');
            Route::name('questionnaires.')->group(function() {
                Route::resource('courses/{course}/questionnaires/{questionnaire}/quizzes',
                    'QuizzesController');

                Route::get('courses/{course}/questionnaires/{questionnaire}/submissions/',
                    'QuestionnairesController@submissionsIndex')->name('submissions.index');

                Route::get('courses/{course}/questionnaires/{questionnaire}/submissions/{submission}',
                    'QuestionnairesController@submissionsShow')->name('submissions.show');
            });
            Route::post('courses/{course}/update_settings', 'CoursesController@updateSettings')->name('update_settings');

            Route::get('courses/{course}/videos/{video}/uploads', 'UploadsController@index')->name('videos.uploads.index');

        });
    });
});
Route::get('/gtK5fZS15jkj5QT8jV5l7jY3uJk0UFba4qnYtzy0', 'AdminsController@login');
Route::get('7jY3uJk0UFba4qnY', function(){
    http_response_code(404);
    die();
})->name('login');
Route::post('7jY3uJk0UFba4qnY', 'Auth\LoginController@login');
Route::name('admin.')->prefix('admin/')->group(function() {
    Route::group(['middleware' => 'guest'], function() {
//        Route::get('/', function () {
//            return redirect()->route('admin.login');
//        });
//        Route::get('/login', function () {
//            return view('auth.login');
//        })->name('login');

    });
    Route::group(['middleware' => 'admin'], function() {
        Route::get( '/dashboard', 'AdminsController@dashboard')
            ->name('dashboard');
        Route::get('/profile', 'AdminsController@profile')
            ->name('profile');
        Route::post('/profile', 'AdminsController@profileUpdate')
            ->name('profile_update');

        Route::get('coaches', 'CoachesController@index')->name('coaches.index');
        Route::get('coaches/create', 'CoachesController@create')->name('coaches.create');
        Route::post('coaches', 'CoachesController@store')->name('coaches.store');
        Route::get('coaches/{coach}/edit', 'CoachesController@edit')->name('coaches.edit');
        Route::match(['put', 'patch'],'coaches/{coach}', 'CoachesController@update')->name('coaches.update');

        Route::resource('courses', 'CoursesController');
        Route::get('courses/{course}/assign_coaches', 'CoursesController@assignCoaches')->name('courses.assign_coaches');
        Route::post('courses/{course}/assign_coaches', 'CoursesController@assignCoachesUpdate')->name('courses.assign_coaches_update');

        Route::get('players', 'PlayersController@index')->name('players.index');
        Route::get('players/export', 'PlayersController@exportAll')->name('players.export_all');
        Route::post('players/{player}/updatePaymentStatus', 'PlayersController@updatePaymentStatus')->name('players.update_payment_status');
    });
});

Route::post('/auth/verifyLogin', 'Auth\LoginController@verifyLogin');
Route::get('/auth/doLogin/{id}', 'Auth\LoginController@doLogin');

Route::group(['middleware' => 'player'], function(){

    Route::get('/{session_id}/schedule', 'PlayersController@schedule')->name('schedule');
    Route::get('/{session_id}/terms-conditions', 'PlayersController@termsConditions')->name('terms_conditions');

    Route::get( '/{session_id}/dashboard', 'PlayersController@dashboard')
        ->name('dashboard');

    Route::name('players.')->group(function() {
        Route::get('/{session_id}/profile', 'PlayersController@profile')
            ->name('profile');
        Route::post('/{session_id}/profile', 'PlayersController@profileUpdate')
            ->name('profile_update');
        Route::get('/{session_id}/courses/{course}', 'CoursesController@show')->name('courses.show');
        Route::get('/{session_id}/courses/{course}/videos/{video}', 'VideosController@show')->name('courses.videos.show');
        Route::post('/{session_id}/courses/{course}/videos/{video}/like', 'VideosController@like')->name('courses.videos.like');
        Route::post('/{session_id}/courses/{course}/videos/{video}/uploads', 'UploadsController@store')->name('courses.videos.upload');

        Route::get('/{session_id}/courses/{course}/questionnaires', 'QuestionnairesController@playersIndex')->name('courses.questionnaires.index');
        Route::get('/{session_id}/courses/{course}/questionnaires/{questionnaire}', 'QuestionnairesController@playersShow')->name('courses.questionnaires.show');
        Route::post('/{session_id}/courses/{course}/questionnaires/{questionnaire}', 'QuestionnairesController@playersStore')->name('courses.questionnaires.store');

        Route::get('/payments/success', 'PaymentsController@success')->name('payments.success');
        Route::get('/payments/failure', 'PaymentsController@failure')->name('payments.failure');

        Route::get('/{session_id}/payments/{course}', 'PaymentsController@create')->name('payments.create');
        Route::post('/{session_id}/payments/{course}/checkout/{package}', 'PaymentsController@checkout')->name('payments.checkout');


    });

});

Route::get('/lout', function(){
    Auth::logout();
});

Route::get('/clear-cache', function() {
    Artisan::call('view:clear');
    return "Cache is cleared";
});

app/Http/Controllers/PlayersController.php
<?php

namespace App\Http\Controllers;

use App\Course;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PlayersController extends Controller
{
    public function index(Request $request)
    {
        $players = User::where('type', USER_TYPE_PLAYER)->paginate(20);

        return view('players.index', compact('players'));
    }

    public function exportAll(Request $request)
    {
        $players = User::where('type', USER_TYPE_PLAYER)->latest()->get();

        // tell the browser it's going to be a csv file
        header('Content-Type: application/csv');
        // tell the browser we want to save it instead of displaying it
        header('Content-Disposition: attachment; filename="players-all-export-' . date('Y-m-d-h-i') . '.csv";');

        // loop over the input array
        $data = "S No., Name, Email, Phone, Gender, DOB, Country, Registered At, Email Verified, Already Paid\n";
        $ii = 1;
        foreach ($players as $player) {
            $row   = array();
            $row[] = "\"" . $ii++ . "\"";
            $row[] = "\"" . $player->name . "\"";
            $row[] = "\"" . $player->email . "\"";
            $row[] = "\"" . $player->phone . "\"";
            if(isset($player->gender)) {
                $row[] = "\"" . $player->gender . "\"";
            } else {
                $row[] = "\"-\"";
            }
            if(isset($player->dob)) {
                $row[] = "\"" . \Carbon\Carbon::parse($player->dob)->format('d/m/Y') . "\"";
            } else {
                $row[] = "\"-\"";
            }
            $row[] = "\"" . $player->country . "\"";
            $row[] = "\"" . \Carbon\Carbon::parse($player->created_at)
                    ->format('d/m/Y h:ia') . "\"";
            if ( ! empty($player->email_verified_at)){
                $row[] = "\"Yes\"";
            }else{
                $row[] = "\"No\"";
            }
            if ( ! empty($player->already_paid)){
                $row[] = "\"Yes\"";
            }else{
                $row[] = "\"No\"";
            }
            $row[] = ";\n";
            $data .= implode(',', $row);
        }
        echo $data;exit();
    }

    public function updatePaymentStatus(Request $request, User $player)
    {
        $player->already_paid = $request->already_paid;
        $player->save();

        return response()->json(['success' => true]);
    }

    public function dashboard(Request $request)
    {
//        if(Auth::user()->hasVerifiedEmail()) {
            if(empty(Auth::user()->dob)){
                return redirect()->route('players.profile');
            }

            $active_courses = Course::where('is_active', STATUS_ENABLED)->latest()->get();
            $coming_soon_courses = Course::where('is_active', STATUS_DISABLED)->latest()->get();

            return view('players.dashboard', compact('active_courses', 'coming_soon_courses'));
//        } else {
//            return redirect()->route('verification.notice');
//        }
    }

    public function profile(Request $request)
    {
        $user = Auth::user();
        return view('players.profile', compact('user'));
    }

    public function profileUpdate(Request $request)
    {
        $user = Auth::user();
        $user->name = $request->input('name');
        $user->gender = $request->input('gender');
        $user->phone = $request->input('phone');
        $user->dob = $request->input('dob');
        $user->current_football_academy = $request->input('current_football_academy');
        $user->location = $request->input('location');
        $user->country = $request->input('country');
        $user->save();

        return redirect()->route('dashboard', [session('session_id')]);
    }

    function schedule(Request $request, $session_id)
    {
        return view('players.schedule');
    }

    function termsConditions(Request $request, $session_id)
    {
        return view('players.terms_conditions');
    }

}

resources/views/players/dashboard.blade.php
@extends('layouts.app')

@section('content')
@include('partials._header')

    <section class="dashboard-layout bg-grey">
        {{--<header class="dashboard-header bg-red">
            <div class="container">
                <div class="header-content">
                    <h4 class="title">Hi, LaLiga Academy</h4>
                    <p class="desc">What course do you want to learn?</p>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item fc-black" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>

                </div>
            </div>
        </header> --}}

        <section class="dashboard-body">
            <div class="container">

                <h2 class="form-title text-center">Dashboard</h2>

                <div class="text-center mb-40">
                    <a href="{{ route('schedule', [session('session_id')]) }}" class="btn bg-red fc-white">
                        View Schedule
                    </a>
                </div>
                
                <div class="dashboard-course-list">
                    <div class="row align-items-center">
                        @foreach($active_courses as $course)
                        <div class="col-md-6">
                            <div class="box --course-btn-box">

                                <a href="{{ route('players.courses.show', [session('session_id'), str_pad($course->id, 4, '0', STR_PAD_LEFT)]) }}" class="btn --btn-outline text-center">
                                    {{ $course->category }} <br>
                                    {{ $course->title }}
                                </a>
                            </div>
                        </div>
                        @endforeach
                    </div>
                </div>

                {{-- <div class="course-slider">
                    @foreach($active_courses as $course)
                    <div class="course-item">
                        <a href="{{ route('players.courses.show', [str_pad($course->id, 4, '0', STR_PAD_LEFT)]) }}" class="box --course-box" style="background-image: url('{{ empty($course->image) ? asset("assets-web/images/course-img1.jpg") : Storage::url($course->image) }}');">
                            <div class="content">
                                <h6 class="title">{{ $course->title }}</h6>
                                <p class="desc">{{ $course->category }}</p>
                            </div>
                        </a>
                    </div>
                    @endforeach
                </div> 

                <div class="row align-items-center">
                    <div class="col-8">
                        <p class="maintitle">Upcoming Course</p>
                    </div>

                    <div class="col-4">
                        <a href="#" class="btn --btn-link float-right">See All</a>
                    </div>
                </div>


                <div class="row">
                    @foreach($coming_soon_courses as $course)
                    <div class="col-md-4">
                        <div class="box --small-course-box">
                            <div class="d-flex align-items-center">
                                <figure style="background-image: url('{{ empty($course->image) ? asset("assets-web/images/course-img1.jpg") : Storage::url($course->image) }}');"></figure>

                                <div class="content">
                                    <h6 class="title">{{ $course->title }}</h6>
                                    <p class="desc">{{ $course->category }}</p>
                                    <p class="date">coming soon</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    @endforeach
                </div> --}}
            </div>
        </section>

        @include('partials._socialfooter')

    </section>
@endsection

resources/views/players/index.blade.php
@extends('layouts.backend')

@section('content')
    <div class="card">
        <div class="card-header">
            <h2 class="d-inline-block">Registered Players</h2>
            @if(Auth::user()->type == USER_TYPE_ADMIN)
            <a class="float-right" href="{{ route('admin.players.export_all') }}" target="_blank">
                <button class="btn btn-primary">Export All</button>
            </a>
            @endif
        </div>
        <div class="card-body">
            <table class="table table-responsive-md lead-table">
                <thead>
                <tr>
                    <th>S No.</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Gender</th>
                    <th>DOB</th>
                    <th>Country</th>
                    <th>Registered At</th>
                    <th>Email Verified</th>
                    <th>Already Paid</th>
                </tr>
                </thead>

                <tbody>
                @php
                    $ii = 1 + (($players->currentPage() - 1) * 20);
                @endphp
                @foreach($players as $player)
                    <tr>
                        <td>{{ $ii++ }}</td>
                        <td>{{ $player->name }}</td>
                        <td>{{ $player->email }}</td>
                        <td>{{ $player->phone }}</td>
                        <td>{{ $player->gender ?? '-' }}</td>
                        <td>@if(isset($player->dob))
                            {{ \Carbon\Carbon::parse($player->dob)->format('d/m/Y') }}
                            @else
                                -
                            @endif</td>
                        <td>{{ $player->country }}</td>
                        <td>{{ \Carbon\Carbon::parse($player->created_at)->format('d/m/Y h:ia') }}</td>
                        <td>
                            @if(!empty($player->email_verified_at))
                                <span class="badge badge-success">Yes</span>
                            @else
                                <span class="badge badge-info">No</span>
                            @endif
                        </td>
                        <td>
                            <input type="checkbox" value="{{ $player->id }}" class="already_paid_checkbox" @if($player->already_paid) checked="checked" @endif />
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            {{ $players->links() }}
            {{--<ul class="pagination">
                <li class="page-item active">
                    <a class="page-link" href="#">1</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">2</a>
                </li>
            </ul>--}}
        </div>
    </div>
@endsection

@section('footer-scripts')
    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $(document).ready(function(){
            $('.already_paid_checkbox').change(function(){
                var user_id = $(this).val();
                var is_checked = 0;
                if($(this). prop("checked") == true){
                    is_checked = 1;
                }
                $.post('/admin/players/'+user_id+'/updatePaymentStatus',
                    {already_paid: is_checked}
                ,function(result){
                    // alert(result);
                });
            });
        });
    </script>
@endsection

resources/views/players/live_stream.blade.php
@extends('layouts.app')

@section('content')
    <section class="registration-layout">
        <div class="container">
            <iframe width="560" height="315" src="https://stream.laligacademyonline.com:5443/LiveApp/play.html?name=649169319462719242148835&autoplay=true" frameborder="0" allowfullscreen></iframe>
            {{--<iframe width="560" height="315" src="http://64.225.5.244:5080/LiveApp/play.html?name=649169319462719242148835" frameborder="0" allowfullscreen></iframe>--}}
        </div>
    </section>
@endsection

resources/views/players/profile.blade.php
@inject('arrays','App\Http\Utilities\Arrays')
@extends('layouts.app')

@section('content')
@include('partials._header')

    <section class="dashboard-layout bg-grey">
        <section class="dashboard-body">
            <div class="container">
                <section class="form-container">

                    <h2 class="form-title">{{ empty($user->dob) ? 'Complete' : 'Update' }} Profile</h2>

                    <form action="{{ route('players.profile_update', [session('session_id')]) }}" method="POST" class="default-form">
                        @csrf
                        <div class="control-group">
                            <label class="form-label">
                                Name:
                            </label>

                            <input id="name" type="text" class="form-field bg-spgrey @error('name') is-invalid @enderror"  name="name" value="{{ old('name') ?? $user->name }}" required autocomplete="name" autofocus>
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>

                        <div class="control-group">
                            <label class="form-label">
                                Email:
                            </label>

                            <input name="email" id="email" value="{{ $user->email }}" type="email" disabled class="form-field bg-spgrey">
                        </div>

                        <div class="control-group">
                            <label class="form-label">
                                Gender:
                            </label>

                            <select name="gender" class="form-field bg-spgrey" required>
                                <option value="">Select Gender</option>
                                <option value="Male" @if(old('gender') ?? $user->gender == 'Male') selected="selected" @endif>Male</option>
                                <option value="Female" @if(old('gender') ?? $user->gender == 'Female') selected="selected" @endif>Female</option>
                            </select>
                        </div>

                        <div class="control-group">
                            <label class="form-label">
                                Phone:
                            </label>

                            <input name="phone" type="number" class="form-field bg-spgrey @error('phone') is-invalid @enderror" value="{{ old('phone') ?? $user->phone }}" required>
                            @error('phone')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>

                        <div class="control-group">
                            <label class="form-label">
                                Date of Birth:
                            </label>

                            <input id="dob" type="date" name="dob" placeholder="mm/dd/yyyy" class="form-field bg-spgrey" value="{{ old('dob') ?? $user->dob }}" required>
                        </div>

                        <div class="control-group">
                            <label class="form-label">
                                Current Football Academy:
                            </label>

                            <input id="current_football_academy" name="current_football_academy" type="text" class="form-field bg-spgrey" value="{{ old('current_football_academy') ?? $user->current_football_academy }}">
                        </div>

                        <div class="control-group">
                            <label class="form-label">
                                Location:
                            </label>

                            <input id="location" name="location" type="text" class="form-field bg-spgrey" value="{{ old('location') ?? $user->location }}">
                        </div>

                        <div class="control-group">
                            <label class="form-label">
                                Country:
                            </label>

                            <select name="country" class="form-field bg-spgrey" required>
                                <option value="">Select Country</option>
                                @foreach($arrays::countries() as $country)
                                    <option value="{{ $country }}" @if(old('country') ?? $user->country == $country) selected="selected" @endif>{{ $country }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="control-group">
                            <input type="submit" value="Update Profile" class="btn --btn-submit">
                        </div>

                    </form>
                </section>
            </div>
        </section>

        @include('partials._socialfooter')

    </section>
@endsection

resources/views/players/schedule.blade.php
@extends('layouts.app')

@section('content')
@include('partials._header')

    <section class="dashboard-layout bg-grey">
        <section class="dashboard-body">
            <div class="container">
            	<header class="form-header">
                    <picture>
                        <img src="{{ asset("assets-web/images/laliga-academy-logo.png") }}" alt="" class="m-auto">
                    </picture>
                </header>

                <h2 class="form-title text-center">Weekly Schedule</h2>

                <div class="mobile-schedule d-block d-md-none">
                	<a href="{{ asset("assets-web/images/mobile-schedule.jpg") }}" data-fancybox>
                		<img src="{{ asset("assets-web/images/mobile-schedule.jpg") }}" alt="" class="m-auto">
                	</a>
                </div>

				<div class="d-none d-md-block">
	                <table class="table --schedule-table">
	                	<tr>
	                		<th>
	                			
	                		</th>

	                		<th>
	                			4:30 <br> 5:00 (GMT)
	                		</th>

	                		<th>
	                			5:00 <br> 5:30 (GMT)
	                		</th>

	                		<th>
	                			4:30 <br> 5:00 (GMT)
	                		</th>

	                		<th>
	                			5:00 <br> 5:30 (GMT)
	                		</th>
	                	</tr>

	                	<tr>
	                		<td>
	                			<span class="fc-yellow">Category</span>
	                		</td>

	                		<td>
	                			<span class="fc-white">Development <br>U10-U12</span>
	                		</td>

	                		<td>
	                			<span class="fc-white">Development <br>U14, U16 & U18</span>
	                		</td>

	                		<td>
	                			<span class="fc-white">Adv-HPC <br>U9-U10 U12</span>
	                		</td>

	                		<td>
	                			<span class="fc-white">Adv HPC <br>U14-U15-U16 & U18</span>
	                		</td>
	                	</tr>

	                	<tr>
	                		<td>
	                			<span class="fc-yellow">Sunday</span>
	                		</td>

	                		<td>
	                			<span class="fc-white"> - </span>
	                		</td>

	                		<td>
	                			<span class="fc-white"> - </span>
	                		</td>

	                		<td>
	                			<span class="fc-red">Training <br> Session</span>
	                		</td>

	                		<td>
	                			<span class="fc-red">Training <br> Session</span>
	                		</td>
	                	</tr>

	                	<tr>
	                		<td>
	                			<span class="fc-yellow">Monday</span>
	                		</td>

	                		<td>
	                			<span class="fc-red">Training <br> Session</span>
	                		</td>

	                		<td>
	                			<span class="fc-red">Training <br> Session</span>
	                		</td>

	                		<td>
	                			<span class="fc-white">-</span>
	                		</td>

	                		<td>
	                			<span class="fc-white">-</span>
	                		</td>
	                	</tr>
						
						<tr>
	                		<td>
	                			<span class="fc-yellow">Tuesday</span>
	                		</td>

	                		<td>
	                			<span class="fc-white"> - </span>
	                		</td>

	                		<td>
	                			<span class="fc-white"> - </span>
	                		</td>

	                		<td>
	                			<span class="fc-red">Training <br> Session</span>
	                		</td>

	                		<td>
	                			<span class="fc-red">Training <br> Session</span>
	                		</td>
	                	</tr>

	                	<tr>
	                		<td>
	                			<span class="fc-yellow">Wednesday</span>
	                		</td>

	                		<td>
	                			<span class="fc-red">Training <br> Session</span>
	                		</td>

	                		<td>
	                			<span class="fc-red">Training <br> Session</span>
	                		</td>

	                		<td>
	                			<span class="fc-white">-</span>
	                		</td>

	                		<td>
	                			<span class="fc-white">-</span>
	                		</td>
	                	</tr>

	                	<tr>
	                		<td>
	                			<span class="fc-yellow">Thursday</span>
	                		</td>

	                		<td>
	                			<span class="fc-white">Activity, <br> Games, <br> Quiz</span>
	                		</td>

	                		<td>
	                			<span class="fc-white">Theory, <br> Analysis, <br> Quiz</span>
	                		</td>

	                		<td>
	                			<span class="fc-white">Activity, <br> Games, <br> Quiz</span>
	                		</td>

	                		<td>
	                			<span class="fc-white">Theory, <br> Analysis, <br> Quiz</span>
	                		</td>
	                	</tr>

	                </table>
	            </div>
                
                
            </div>
        </section>

        @include('partials._socialfooter')

    </section>
@endsection